# Generated by Django 2.2.3 on 2019-08-07 08:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DLS', '0002_DLS'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DLS',
            new_name='DLSuser',
        ),
    ]
